### ISSUE TITLE
Marshmallow Date field does not align with the pyspark DateType field

### ISSUE THREAD

**Issue by petruf** [ketgo/marshmallow-pyspark#2]
Hello ketgo,
thank you for the great library. I am using it for a project and I run into the following issue:
The mapping from the documentation page is not working as the fields.Date() expects Pyspark schema type StringType and not DateType.
Following example ends with TypeError: Object of type date is not JSON serializable
but the df.schema and AlbumSchema().spark_schema are the same.

Could it be changed so that marshmallow-pyspark validates the schema with DateType and the original field functionality is tied to something like DateStringType?

Thank you

P.

```
import datetime
from marshmallow_pyspark import Schema
from marshmallow import fields

# Create data schema.
class AlbumSchema(Schema):
    title = fields.Str()
    release_date = fields.Date()

# Input data frame to validate.
df = spark.createDataFrame([
    {"title": "valid_1", "release_date": datetime.date(2020, 1, 10)},
    {"title": "valid_2", "release_date": datetime.date(2020, 1, 11)},
    {"title": "invalid_1", "release_date": datetime.date(2020, 1, 11)},
    {"title": "invalid_2", "release_date": datetime.date(2020, 1, 21)},
])

# Get data frames with valid rows and error prone rows 
# from input data frame by validating using the schema.
valid_df, errors_df = AlbumSchema().validate_df(df)

# Output of valid data frame
valid_df.show()
#    +-------+------------+
#    |  title|release_date|
#    +-------+------------+
#    |valid_1|  2020-01-10|
#    |valid_2|  2020-01-11|
#    +-------+------------+

# Output of errors data frame
errors_df.show()
#    +--------------------+
#    |             _errors|
#    +--------------------+
#    |{"row": {"release...|
#    |{"row": {"release...|
#    +--------------------+

print(df.schema)
print(AlbumSchema().spark_schema)
```

**Comment by ketgo** [comment]
Hi @petruf 

Thanks for reporting the issue! 

The issue you are facing can be traced back to how marshmallow handles datetimes (see [656](https://github.com/marshmallow-code/marshmallow/issues/656)). There are two workarounds I can think of currently:

1. Support a custom marshmallow field called `DateObject` and `DateTimeObject` which takes a python `date` and `datetime` object as input during de-serialization and performs no formatting.

2. Expanding on the above idea, add support for marshmallow [`Raw`](https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Raw) field type. The underlying convertor checks for the type of object and uses the appropriate pyspark type.

Let me know what you think.

Thanks!

**Comment by petruf** [comment]
Hello Ketan,
thank you for answering. I tried creating the custom DateObject which works for the date spark columns without error but once I try to validate a dataframe column which does not comply to the custom field, I get the _TypeError: Object of type date is not JSON serializable_ again. To be honest I don't really understand what causes the issue and why JSON is even mentioned :-( ...

From your comment the second option sounds better to me as the validation is implicit by comparing the pyspark type. But the best would be if one could put there validation range as well, not sure how to implement that.
```
from marshmallow import fields, ValidationError
from datetime import date

class DateObject(fields.Field):
    def _serialize(self, value, attr, obj, **kwargs):
        if value is None:
            return None
        return datetime.strptime(value, "%Y-%m-%d").date()

    def _deserialize(self, value, attr, data, **kwargs):
        if isinstance(value, date):
            try:
                return value.strftime("%Y-%m-%d")
            except ValueError as error:
                raise ValidationError("Not a valid datetime.") from error
        else:
            raise ValidationError("Not a valid datetime.")
```

**Comment by ketgo** [comment]
Hi @petruf, The implementation for the `DateObject` you shown will not work for your usecase. In the `_serialize` and `_deserialize` methods you are assuming a string is being passed while in fact it is a datetime object. Try the following:
```python
from marshmallow import fields, ValidationError
from marshmallow_pyspark import Schema
from marshmallow_pyspark.converters import DateConverter
from datetime import date

class DateObject(fields.Field):
    def _serialize(self, value, attr, obj, **kwargs):
        if value is None:
            return None
        return str(value)

    def _deserialize(self, value, attr, data, **kwargs):
        # The value is already a date object
        if isinstance(value, date):
            return value      
        else:
            raise ValidationError("Not a valid datetime.")

# Create data schema.
class AlbumSchema(Schema):
    title = fields.Str()
    release_date = DateObject()

# Adding converter for dateobject to schema.
AlbumSchema.CONVERTER_MAP[DateObject] = DateConverter

# Input data frame to validate.
df = spark.createDataFrame([
    {"title": "valid_1", "release_date": date(2020, 1, 10)},
    {"title": "valid_2", "release_date": date(2020, 1, 11)},
    {"title": "invalid_1", "release_date": date(2020, 1, 11)},
    {"title": "invalid_2", "release_date": date(2020, 1, 21)},
])

# Get data frames with valid rows and error prone rows 
# from input data frame by validating using the schema.
valid_df, errors_df = AlbumSchema().validate_df(df)

```

**Comment by ketgo** [comment]
Hi @petruf. Added the Raw field in the new release. This [unit test](https://github.com/ketgo/marshmallow-pyspark/blob/master/tests/test_fields.py) shows how you can implement your use-case. Closing this issue for now. Please feel free to re-open it if required. Thanks!
