### ISSUE TITLE
TypeError: Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by ashwin153** [ketgo/marshmallow-pyspark#4]
When an invalid row contains a `datetime` field, JSON serialization fails at runtime.

```python
schema = marshmallow_pyspark.Schema.from_dict({
    "time": datetime.datetime,
    "repro": float,
})()

_, errors = schema.validate_df(spark.createDataFrame([
    {"time": datetime.datetime.now(), "repro": "invalid"},
]))

errors.show()
# TypeError: Object of type datetime is not JSON serializable
```

**Comment by ashwin153** [comment]
A simple fix is to use `default=str` when calling `json.dumps`. (https://stackoverflow.com/a/36142844)

https://github.com/ketgo/marshmallow-pyspark/blob/7ab6229ef6aa05184a15a8ee574eef9ceb8f54e9/marshmallow_pyspark/schema.py#L71-L76

**Comment by ketgo** [comment]
Thanks for the PR.
