### ISSUE TITLE
Update marshmallow-oneofschema dependency

### ISSUE THREAD

**Issue by buseynehannes** [ketgo/marshmallow-pyspark#6]
This package is currently dependening on an [older version of marshmallow-oneofschema](https://github.com/ketgo/marshmallow-pyspark/blob/master/setup.py#L29) 

The newer versions of this package have a lot of performance increases, but due to a conflict with this package we are currently unable to upgrade ([changelog](https://github.com/marshmallow-code/marshmallow-oneofschema/blob/master/CHANGELOG.rst))
Would be great if the dependency could be upgraded.

**Comment by ketgo** [comment]
Hi @buseynehannes, would you like to open a PR for this? It might take some time for me to work on this.

**Comment by buseynehannes** [comment]
Hi Ketgo, thanks for the response
seems like it's compatible with the new version out of the box: https://github.com/ketgo/marshmallow-pyspark/pull/8
